# Generated by Django 5.1.5 on 2025-02-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_faq_answer_bn_remove_faq_answer_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='question_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
    ]
